#!/bin/sh
#
# ~/.xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export EDITOR="vim"
export VIRTUALENV_USE_DISTRIBUTE=1

if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

numlockx &
sh ~/.fehbg &
dropboxd &
(mpd && sleep 3 && urxvt -e tmux -u attach -t 0) &

exec dbus-launch python ~/bin/dwm/launcher.py
